stages:
  - package
  - publish

package:jessie:gem:
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-ruby
  stage: package
  variables:
    DISTRO: jessie
    GEMFILE: netlinkrb.gemspec
  script:
    - sysctl -a | grep ipv6
    - ip -6 a
    - package
  artifacts:
    paths:
    - pkg/
 
package:jessie: &package
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-deb
  stage: package
  variables:
    DISTRO: jessie
  script:
    - package
  artifacts:
    paths:
      - pkg/

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

package:wheezy:
  <<: *package
  variables:
    DISTRO: wheezy

publish:
  image: $CI_REGISTRY/docker-images/layers:jessie-publish
  stage: publish
  script:
    - publish

