stages:
  - package
  - publish
 
package:jessie: &package
  stage: package
  tags:
    - shell
  variables:
    DISTRO: jessie
  script:
    - sautobuild -d $DISTRO -- --debuild-flags=-b $PWD
    - mkdir -p pkg/$DISTRO
    - mv -v ../*.{dsc,build,buildinfo,changes,tar.*} pkg/$DISTRO 2>/dev/null || true
    - mv -v ../*.deb pkg/$DISTRO
  artifacts:
    paths:
      - pkg/

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

package:wheezy:
  <<: *package
  variables:
    DISTRO: wheezy

publish:
  stage: publish
  script:
    - publish

