stages:
  - package
  - publish
 
package:jessie: &package
  stage: package
  tags:
    - shell
  variables:
    DISTRO: jessie
  script:
    - export VERSION=$(git tag --contains master --merged master)
    - git archive -v --format tgz -o ../ruby-linux-netlink_$VERSION.orig.tar.gz master
    - git checkout debian/$DISTRO
    - sautobuild -d $DISTRO $PWD
  artifacts:
    paths:
      - pkg/

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

publish:
  stage: publish
  tags: 
    - shell
  script:
    - publish

