stages:
  - package
  - publish
 
package:jessie: &package
  stage: package
  tags:
    - shell
  variables:
    DISTRO: jessie
  script:
    - git checkout debian/$DISTRO
    - sautobuild $PWD
  artifacts:
    paths:
      - pkg/

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

publish:
  stage: publish
  tags: 
    - shell
  script:
    - publish

