require 'socket'
class Socket
  # From /usr/include/bits/socket.h
  PF_NETLINK		= 16		unless defined? Socket::PF_NETLINK
  AF_NETLINK		= PF_NETLINK	unless defined? Socket::AF_NETLINK
end

module Netlink
  # From linux/netlink.h
  NETLINK_ROUTE		= 0
  NETLINK_UNUSED	= 1
  NETLINK_USERSOCK	= 2
  NETLINK_FIREWALL	= 3
  NETLINK_INET_DIAG	= 4
  NETLINK_NFLOG		= 5
  NETLINK_XFRM		= 6
  NETLINK_SELINUX	= 7
  NETLINK_ISCSI		= 8
  NETLINK_AUDIT		= 9
  NETLINK_FIB_LOOKUP	= 10
  NETLINK_CONNECTOR	= 11
  NETLINK_NETFILTER	= 12
  NETLINK_IP6_FW	= 13
  NETLINK_DNRTMSG	= 14
  NETLINK_KOBJECT_UEVENT = 15
  NETLINK_GENERIC	= 16
  NETLINK_SCSITRANSPORT	= 18
  NETLINK_ECRYPTFS	= 19
  
  NLM_F_REQUEST		= 1
  NLM_F_MULTI		= 2
  NLM_F_ACK		= 4
  NLM_F_ECHO		= 8
  NLM_F_ROOT		= 0x100
  NLM_F_MATCH		= 0x200
  NLM_F_ATOMIC		= 0x400
  NLM_F_DUMP		= (NLM_F_ROOT|NLM_F_MATCH)
  
  NLM_F_REPLACE		= 0x100
  NLM_F_EXCL		= 0x200
  NLM_F_CREATE		= 0x400
  NLM_F_APPEND		= 0x800

  NLMSG_ALIGNTO		= 4
  
  NLMSG_NOOP		= 0x1
  NLMSG_ERROR		= 0x2
  NLMSG_DONE		= 0x3
  NLMSG_OVERRUN		= 0x4
  
  NETLINK_ADD_MEMBERSHIP	= 1
  NETLINK_DROP_MEMBERSHIP	= 2
  NETLINK_PKTINFO		= 3
  NETLINK_BROADCAST_ERROR	= 4
  NETLINK_NO_ENOBUFS		= 5
  
  NETLINK_UNCONNECTED		= 0
  NETLINK_CONNECTED		= 1
  
  NLA_F_NESTED			= (1 << 15)
  NLA_F_NET_BYTEORDER		= (1 << 14)
  NLA_TYPE_MASK			= ~(NLA_F_NESTED | NLA_F_NET_BYTEORDER)
  
  NLA_ALIGNTO			= 4
  
  # from linux/rtnetlink.h.
  # Should we put each of these groups under separate namespace?
  #   Netlink::Message::GETROUTE
  #   Netlink::Route::Type::UNICAST
  #   Netlink::Route::Protocol::STATIC
  RTM_NEWLINK		= 16
  RTM_DELLINK		= 17
  RTM_GETLINK		= 18
  RTM_SETLINK		= 19
  
  RTM_NEWADDR		= 20     
  RTM_DELADDR		= 21
  RTM_GETADDR		= 22
  
  RTM_NEWROUTE		= 24
  RTM_DELROUTE		= 25
  RTM_GETROUTE		= 26
  
  RTM_NEWNEIGH		= 28
  RTM_DELNEIGH		= 29
  RTM_GETNEIGH		= 30
  
  RTM_NEWRULE		= 32
  RTM_DELRULE		= 33
  RTM_GETRULE		= 34
  
  RTM_NEWQDISC		= 36
  RTM_DELQDISC		= 37
  RTM_GETQDISC		= 38
  
  RTM_NEWTCLASS		= 40
  RTM_DELTCLASS		= 41
  RTM_GETTCLASS		= 42
  
  RTM_NEWTFILTER	= 44
  RTM_DELTFILTER	= 45
  RTM_GETTFILTER	= 46
  
  RTM_NEWACTION		= 48
  RTM_DELACTION		= 49
  RTM_GETACTION		= 50
  
  RTM_NEWPREFIX		= 52
  RTM_GETMULTICAST	= 58
  RTM_GETANYCAST	= 62

  RTM_NEWNEIGHTBL	= 64
  RTM_GETNEIGHTBL	= 66
  RTM_SETNEIGHTBL	= 67
  
  RTM_NEWNDUSEROPT	= 68

  RTM_NEWADDRLABEL	= 72
  RTM_DELADDRLABEL	= 73
  RTM_GETADDRLABEL	= 74
  
  RTM_GETDCB		= 78
  RTM_SETDCB		= 79

  # Route#type
  
  RTN_UNSPEC		= 0
  RTN_UNICAST		= 1
  RTN_LOCAL		= 2
  RTN_BROADCAST		= 3
  RTN_ANYCAST		= 4
  RTN_MULTICAST		= 5
  RTN_BLACKHOLE		= 6
  RTN_UNREACHABLE	= 7
  RTN_PROHIBIT		= 8
  RTN_THROW		= 9
  RTN_NAT		= 10
  RTN_XRESOLVE		= 11
  
  # Route#protocol
  
  RTPROT_UNSPEC		= 0
  RTPROT_REDIRECT	= 1
  RTPROT_KERNEL		= 2
  RTPROT_BOOT		= 3
  RTPROT_STATIC		= 4
  
  # MORE TO GO
end
