require 'socket'
class Socket
  # From bits/socket.h
  PF_NETLINK		= 16		unless defined? Socket::PF_NETLINK
  AF_NETLINK		= PF_NETLINK	unless defined? Socket::AF_NETLINK
end

module Netlink
  # From linux/netlink.h
  NETLINK_ROUTE		= 0
  NETLINK_UNUSED	= 1
  NETLINK_USERSOCK	= 2
  NETLINK_FIREWALL	= 3
  NETLINK_INET_DIAG	= 4
  NETLINK_NFLOG		= 5
  NETLINK_XFRM		= 6
  NETLINK_SELINUX	= 7
  NETLINK_ISCSI		= 8
  NETLINK_AUDIT		= 9
  NETLINK_FIB_LOOKUP	= 10
  NETLINK_CONNECTOR	= 11
  NETLINK_NETFILTER	= 12
  NETLINK_IP6_FW	= 13
  NETLINK_DNRTMSG	= 14
  NETLINK_KOBJECT_UEVENT = 15
  NETLINK_GENERIC	= 16
  NETLINK_SCSITRANSPORT	= 18
  NETLINK_ECRYPTFS	= 19
  
  NLM_F_REQUEST		= 1
  NLM_F_MULTI		= 2
  NLM_F_ACK		= 4
  NLM_F_ECHO		= 8
  NLM_F_ROOT		= 0x100
  NLM_F_MATCH		= 0x200
  NLM_F_ATOMIC		= 0x400
  NLM_F_DUMP		= (NLM_F_ROOT|NLM_F_MATCH)
  
  NLM_F_REPLACE		= 0x100
  NLM_F_EXCL		= 0x200
  NLM_F_CREATE		= 0x400
  NLM_F_APPEND		= 0x800

  NLMSG_ALIGNTO		= 4
  
  NLMSG_NOOP		= 0x1
  NLMSG_ERROR		= 0x2
  NLMSG_DONE		= 0x3
  NLMSG_OVERRUN		= 0x4
  
  NETLINK_ADD_MEMBERSHIP	= 1
  NETLINK_DROP_MEMBERSHIP	= 2
  NETLINK_PKTINFO		= 3
  NETLINK_BROADCAST_ERROR	= 4
  NETLINK_NO_ENOBUFS		= 5
  
  NETLINK_UNCONNECTED		= 0
  NETLINK_CONNECTED		= 1
  
  NLA_F_NESTED			= (1 << 15)
  NLA_F_NET_BYTEORDER		= (1 << 14)
  NLA_TYPE_MASK			= ~(NLA_F_NESTED | NLA_F_NET_BYTEORDER)
  
  NLA_ALIGNTO			= 4
  
  # from linux/rtnetlink.h.
  # Should we put each of these groups under separate namespace?
  #   Netlink::Message::GETROUTE
  #   Netlink::Route::Type::UNICAST
  #   Netlink::Route::Protocol::STATIC
  RTM_NEWLINK		= 16
  RTM_DELLINK		= 17
  RTM_GETLINK		= 18
  RTM_SETLINK		= 19
  
  RTM_NEWADDR		= 20     
  RTM_DELADDR		= 21
  RTM_GETADDR		= 22
  
  RTM_NEWROUTE		= 24
  RTM_DELROUTE		= 25
  RTM_GETROUTE		= 26
  
  RTM_NEWNEIGH		= 28
  RTM_DELNEIGH		= 29
  RTM_GETNEIGH		= 30
  
  RTM_NEWRULE		= 32
  RTM_DELRULE		= 33
  RTM_GETRULE		= 34
  
  RTM_NEWQDISC		= 36
  RTM_DELQDISC		= 37
  RTM_GETQDISC		= 38
  
  RTM_NEWTCLASS		= 40
  RTM_DELTCLASS		= 41
  RTM_GETTCLASS		= 42
  
  RTM_NEWTFILTER	= 44
  RTM_DELTFILTER	= 45
  RTM_GETTFILTER	= 46
  
  RTM_NEWACTION		= 48
  RTM_DELACTION		= 49
  RTM_GETACTION		= 50
  
  RTM_NEWPREFIX		= 52
  RTM_GETMULTICAST	= 58
  RTM_GETANYCAST	= 62

  RTM_NEWNEIGHTBL	= 64
  RTM_GETNEIGHTBL	= 66
  RTM_SETNEIGHTBL	= 67
  
  RTM_NEWNDUSEROPT	= 68

  RTM_NEWADDRLABEL	= 72
  RTM_DELADDRLABEL	= 73
  RTM_GETADDRLABEL	= 74
  
  RTM_GETDCB		= 78
  RTM_SETDCB		= 79

  # Route#type
  
  RTN_UNSPEC		= 0
  RTN_UNICAST		= 1
  RTN_LOCAL		= 2
  RTN_BROADCAST		= 3
  RTN_ANYCAST		= 4
  RTN_MULTICAST		= 5
  RTN_BLACKHOLE		= 6
  RTN_UNREACHABLE	= 7
  RTN_PROHIBIT		= 8
  RTN_THROW		= 9
  RTN_NAT		= 10
  RTN_XRESOLVE		= 11
  
  # Route#protocol
  
  RTPROT_UNSPEC		= 0
  RTPROT_REDIRECT	= 1
  RTPROT_KERNEL		= 2
  RTPROT_BOOT		= 3
  RTPROT_STATIC		= 4
  
  # XXXX MORE TO GO

  RTA_UNSPEC		= 0
  RTA_DST		= 1
  RTA_SRC		= 2
  RTA_IIF		= 3
  RTA_OIF		= 4
  RTA_GATEWAY		= 5
  RTA_PRIORITY		= 6
  RTA_PREFSRC		= 7
  RTA_METRICS		= 8
  RTA_MULTIPATH		= 9
  RTA_FLOW		= 11
  RTA_CACHEINFO		= 12
  RTA_TABLE		= 15
  
  # from linux/if_link.h
  IFLA_UNSPEC		= 0
  IFLA_ADDRESS		= 1
  IFLA_BROADCAST	= 2
  IFLA_IFNAME		= 3
  IFLA_MTU		= 4
  IFLA_LINK		= 5
  IFLA_QDISC		= 6
  IFLA_STATS		= 7
  IFLA_COST		= 8
  IFLA_PRIORITY		= 9
  IFLA_MASTER		= 10
  IFLA_WIRELESS		= 11
  IFLA_PROTINFO		= 12
  IFLA_TXQLEN		= 13
  IFLA_MAP		= 14
  IFLA_WEIGHT		= 15
  IFLA_OPERSTATE	= 16
  IFLA_LINKMODE		= 17
  IFLA_LINKINFO		= 18
  IFLA_NET_NS_PID	= 19
  IFLA_IFALIAS		= 20
  IFLA_NUM_VF		= 21
  IFLA_VFINFO_LIST	= 22
  IFLA_STATS64		= 23
  IFLA_VF_PORTS		= 24
  IFLA_PORT_SELF	= 25

  # from linux/if_addr.h
  IFA_UNSPEC		= 0
  IFA_ADDRESS		= 1
  IFA_LOCAL		= 2
  IFA_LABEL		= 3
  IFA_BROADCAST		= 4
  IFA_ANYCAST		= 5
  IFA_CACHEINFO		= 6
  IFA_MULTICAST		= 7
end
